--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/edwinyoo44/ProxyChecker
build-by-default: true
branches:
- master
projects:
  ProxyChecker:
    path: ""
    icon: "/assets/icon.png"
    libs:
      - src: edwinyoo44/libIPGeolocation/libIPGeolocation
        version: ^1.0.1
...
